"""Catalog-backed GoodOption drug research, synthesis, and scoring APIs."""

from .catalog import (
    CATALOG_CHECKPOINT_SCHEMA_VERSION,
    INTERVENTION_EXCLUSION_CATEGORIES,
    INTERVENTION_SCREENING_DISPOSITIONS,
    ROLE_PROMPT_VERSION,
    SYNTHESIS_PROMPT_VERSION,
    build_good_option_catalog,
    build_intervention_screening_messages,
    build_role_resolution_messages,
    build_synthesis_messages,
    load_good_option_catalog,
    validate_good_option_catalog,
)
from .models import (
    CATALOG_SCHEMA_VERSION,
    GOOD_OPTION_INPUT_VERSION,
    GOOD_OPTION_LABEL_SCHEMA_VERSION,
    GOOD_OPTION_PROMPT_VERSION,
    RUBRIC_CRITERIA,
    DrugIdentity,
    DrugSummary,
    EvidencePassage,
    GoodOptionCatalog,
    ParsedGoodOptionResult,
    ResearchAttempt,
    TrialDrugAssignment,
)
from .research import (
    DDGSWebProvider,
    DrugEvidenceSource,
    GeneralWebProvider,
    ResearchSettings,
    build_facet_query,
    default_sources,
    research_drug,
)
from .scoring import (
    build_good_option_checker_text,
    build_good_option_messages,
    evaluate_good_options,
    parse_good_option_response,
    score_good_options,
    score_good_options_with_llm,
)

__all__ = [
    "CATALOG_CHECKPOINT_SCHEMA_VERSION",
    "CATALOG_SCHEMA_VERSION",
    "DDGSWebProvider",
    "DrugEvidenceSource",
    "DrugIdentity",
    "DrugSummary",
    "EvidencePassage",
    "GOOD_OPTION_INPUT_VERSION",
    "GOOD_OPTION_LABEL_SCHEMA_VERSION",
    "GOOD_OPTION_PROMPT_VERSION",
    "GeneralWebProvider",
    "GoodOptionCatalog",
    "INTERVENTION_EXCLUSION_CATEGORIES",
    "INTERVENTION_SCREENING_DISPOSITIONS",
    "ParsedGoodOptionResult",
    "ROLE_PROMPT_VERSION",
    "RUBRIC_CRITERIA",
    "ResearchAttempt",
    "ResearchSettings",
    "SYNTHESIS_PROMPT_VERSION",
    "TrialDrugAssignment",
    "build_facet_query",
    "build_good_option_catalog",
    "build_good_option_checker_text",
    "build_good_option_messages",
    "build_intervention_screening_messages",
    "build_role_resolution_messages",
    "build_synthesis_messages",
    "default_sources",
    "evaluate_good_options",
    "load_good_option_catalog",
    "parse_good_option_response",
    "research_drug",
    "score_good_options",
    "score_good_options_with_llm",
    "validate_good_option_catalog",
]
